### ISSUE TITLE
Parse ISO 8601 with nanosecond resolution

### ISSUE THREAD

**Issue by fzakaria** [jcgertig/nano-date#1]
Date class in Javascript can parse ISO 8601 -- however it would be super useful to do something similar with nano-date

Here is an example: `2017-08-17T17:04:35.155394702Z`

**Comment by jcgertig** [comment]
@fzakaria your changes are now in version 2.0.0 i used the test runner you added to take the chance to get my coverage up and found some small issues so that was very helpful. I had just kept putting it off lol.

**Comment by fzakaria** [comment]
Great glad it helped.

I think some examples of the API in the README is enough and still the example directory should go away :)
