### ISSUE TITLE
TypeError: NanoDate is not a constructor

### ISSUE THREAD

**Issue by dawadam** [jcgertig/nano-date#4]
Hi,
I'm just testing this script with Node (v7.10.1) :

> var NanoDate = require('nano-date')
> const upToMillisecondPrecision  = new NanoDate(1497290225089); // assumes milliseconds
> const upToMicrosecondPrecision  = new NanoDate(1497290225089.999); // assumes milliseconds
> const upToNanosecondPreciion = new NanoDate('1497290225089999999'); // assumes nanoseconds`

But :
> const upToMillisecondPrecision  = new NanoDate(1497290225089); // assumes milliseconds
> ^ TypeError: NanoDate is not a constructor

Any missing?

**Comment by jcgertig** [comment]
hmm ill look into this soon

**Comment by jcgertig** [comment]
@dawadam can you try `var NanoDate = require('nano-date').default;` I'm using the newer export syntax.

**Comment by dawadam** [comment]
Hi, new error is :

> /node_modules/nano-date/lib/index.js:255
>        } else if (a instanceof Date) {
>                     ^
> TypeError: Right-hand side of 'instanceof' is not an object
>    at new NanoDate (/node_modules/nano-date/lib/index.js:255:22)

**Comment by jcgertig** [comment]
Please try the newest version

**Comment by dawadam** [comment]
Ok, work with :

> var NanoDate = require('nano-date').default;

Not with :

> var NanoDate = require('nano-date');

Error is :

> TypeError: NanoDate is not a constructor
