### ISSUE TITLE
Webpack warning due to package.json referencing pre-built JS

### ISSUE THREAD

**Issue by cryptoquick** [jcgertig/nano-date#6]
Here we see main is referencing lib:

https://github.com/jcgertig/nano-date/blob/1f57859a98c1d8fc90e5f56d6e3b69ef2b1f6d41/package.json#L5

I actually can't think of a case where you should do this. It's better to use main to point to unminified source. Otherwise we get this error in Webpack:

```
WARNING in ../~/memoizerific/memoizerific.js
Critical dependencies:
1:485-492 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ../~/memoizerific/memoizerific.js 1:485-492
```

**Comment by jcgertig** [comment]
I'm not minifying. Though the memoize library I use maybe a little.

**Comment by cryptoquick** [comment]
I'm not seeing the error anymore. Not sure what fixed it.
